version: '3'
services:
  rcldnsautorenew:
    image: rclssl/rclssldnsautorenewdocker:1.0.0
    environment:
      - RCLSDK__ClientId=your-client-id
      - RCLSDK__ClientSecret=your-client-secret
      - RCLSDK__TenantId=your-tenent-id
      - RCLSDK__SubscriptionId=your-subscription-id
      - CertificateBot__SaveCertificatePath=/etc/ssl/rcl
      - CertificateBot__IncludeCertificatesArray=example.com
    volumes:
      - rclssl-certs:/etc/ssl/rcl
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - rclssl-certs:/etc/ssl/rcl
volumes:
  rclssl-certs:
    driver: local